Rest of Classes Page
sjl1826/cs130 pull request #69
Opened 2020-11-24 08:35 UTC by Kathirilango

2020-11-24 08:38 UTC, Kathirilango commented
<img width="1409" alt="Screen Shot 2020-11-24 at 12 26 21 AM" src="https://user-images.githubusercontent.com/32283019/100069277-68949880-2ded-11eb-9b44-801d825299b5.png">

2020-11-24 19:26 UTC, shirlyfang requested changes
Most of my review deals with passing the actual user object around to the inviter instead of just the name. because of this we only need the user prop for inviter and we set it to listen to the invitedUser state var when a click on "invite to group happens". otherwise, lgtm.

2020-11-24 19:26 UTC, shirlyfang commented on cs130_front/src/components/Inviter/Inviter.js
> +    props.invitedUser == "" ?
props.user == null ?

2020-11-24 19:26 UTC, shirlyfang commented on cs130_front/src/components/Inviter/Inviter.js
> +      <Text size="24px" weight="800">Invite {props.invitedUser.split(' ')[0]} to group</Text>
```
<Text size="24px" weight="800">Invite {props.user.name.split(' ')[0]} to group</Text>
```

2020-11-24 19:26 UTC, shirlyfang commented on cs130_front/src/components/UserList/UserItem.js
> +          {props.optionalElement ? <Button onClick={ () => props.optionalClick(props.user.name)}> Invite to group </Button> : null}
go back to original

2020-11-24 19:26 UTC, shirlyfang commented on cs130_front/src/components/views/ClassesPage/ClassesPage.js
> +  const [invitedUser, setInvitedUser] = useState('');
const [invitedUser, setInvitedUser] = useState(null);

2020-11-24 19:26 UTC, shirlyfang commented on cs130_front/src/components/views/ClassesPage/ClassesPage.js
> +      setInvitedUser("");
setInvitedUser(null);

2020-11-24 19:26 UTC, shirlyfang commented on cs130_front/src/components/views/ClassesPage/ClassesPage.js
> +              <Inviter user={user} items={items} handleGroupInvite={handleGroupInvite} invitedUser={invitedUser}/>
```
<Inviter user={invitedUser} items={items} handleGroupInvite={handleGroupInvite}/> 
```

2020-11-25 01:08 UTC, shirlyfang approved these changes

2020-11-25 21:05 UTC, merged